# Generated by Django 2.2.4 on 2024-02-20 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='privacy',
            field=models.CharField(default='public', max_length=40, verbose_name='Privacy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 20, 16, 54, 2, 197083, tzinfo=utc), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='default-preview.jpg', upload_to='previews/', verbose_name='Preview of project'),
        ),
    ]
